baseurl = "https://alkn203.github.io/blog/"
languageCode = "ja"
title = "Keep On Coding"
canonifyurls = true
pygmentsCodefences = true
pygmentsUseClasses = true
enableGitInfo = true

[permalinks]
others = ":year/:month/:day/:filename"
tutorials = ":year/:month/:day/:filename"
tips = ":year/:month/:day/:filename"
works = ":year/:month/:day/:filename"

[Params]
subtitle = "Tips and tutorials about phina.js"
description = "Tips and tutorial about phina.js"
author = "alkn203"
authorsite = "https://twitter.com/alkn203"
gravatar = "alkn203@gmail.com"
copyrightYear = "2021"
analytics = "UA-145323973-1"
showsToc = true

[markup.goldmark.renderer]
unsafe = true