baseurl = "https://alkn203.github.io/blog/"
languageCode = "ja"
title = "Keep On Coding"
canonifyurls = true
pygmentsCodefences = true
pygmentsUseClasses = true

[permalinks]
others = ":year/:month/:day/:filename"
tutorials = ":year/:month/:day/:filename"
tips = ":year/:month/:day/:filename"
works = ":year/:month/:day/:filename"

[Params]
subtitle = "Tips and tutorials about phina.js"
description = "Tips and tutorial about phina.js"
author = "alkn203"
gravatar = "alkn203@gmail.com"
copyrightYear = "2020"
twitter = "alkn203"
github = "alkn203"
qiita = "alkn203"
analytics = "UA-145323973-1"
showsToc = true