baseurl = "https://alkn203.github.io/blog/"
languageCode = "ja"
title = "Keep On Coding"
canonifyurls = true
disqusShortname = "alkn203githubio"

[permalinks]
others = ":year/:month/:day/:filename"
tutorials = ":year/:month/:day/:filename"
tips = ":year/:month/:day/:filename"
works = ":year/:month/:day/:filename"

[Params]
subtitle = "javascriptのゲームライブラリphina.js、ゲーム制作、プログラミングなどについて"
author = "alkn203"
profileImage = "/images/alkn203.png"
profileText = "javascript製のゲームライブラリphina.jsを愛用している趣味プログラマ。ファミコン世代。"
copyrightYear = "2019"
twitter = "alkn203"
github = "alkn203"
showsRSS = true
analytics = "UA-145323973-1"
showsShare = true
showsToc = true